### ISSUE TITLE
#为什么GenTLSSignature和CheckTLSSignature 方法添加@Deprecated注释

### ISSUE THREAD

**Issue by jikuodong** [tencentyun/tls-sig-api-java#10]
为什么GenTLSSignature和CheckTLSSignature 方法添加@Deprecated注释，我没看到有替换的新方法啊？

**Comment by CasualJi** [comment]
用这个静态方法“genSig”

**Comment by weijunyi** [comment]
楼上正解，具体可以看 [README](https://github.com/tencentyun/tls-sig-api-java/blob/master/README.md)。
