### ISSUE TITLE
Coding style 混乱

### ISSUE THREAD

**Issue by lzj0396** [tencentyun/tls-sig-api-java#7]
话说能不能格式化一下这些code，以及使用统一的命名规范，看这太扎心了。

**Comment by weijunyi** [comment]
首先，感谢提供反馈。

其次，这里的编码风格确实看起来让人有些不舒服，我们后续会把这里提升下。

最后，如果您实在等不及了，可以给我们提 PR，只要是逻辑没问题，风格 OK 的话，我们很乐意合入。

再次感谢！
