### ISSUE TITLE
GenTLSSignatureResult生成参数不全

### ISSUE THREAD

**Issue by chunmianbujuexiao** [tencentyun/tls-sig-api-java#8]
使用方法GenTLSSignatureEx获取GenTLSSignatureResult时，并没有写入expireTime和initTime。使用方法CheckTLSSignatureEx获取CheckTLSSignatureResult时，expireTime为什么不直接加上initTime。

**Comment by weijunyi** [comment]
这里接口上分为用默认有效期和指定有效期，如 [README](https://github.com/tencentyun/tls-sig-api-java/blob/master/README.md) 中所说，`genSig` 使用的是默认有效期，而 `GenTLSSignatureEx` 可以指定有效期。

另外 `initTime` 是生成 sig 时获取的系统时间，并不需要用户传递。
